package com.koffuxu.myapplication.daogen;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.koffuxu.myapplication.daogen.UserInfo;
import com.koffuxu.myapplication.daogen.FatherUserInfo;

import com.koffuxu.myapplication.daogen.UserInfoDao;
import com.koffuxu.myapplication.daogen.FatherUserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig fatherUserInfoDaoConfig;

    private final UserInfoDao userInfoDao;
    private final FatherUserInfoDao fatherUserInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        fatherUserInfoDaoConfig = daoConfigMap.get(FatherUserInfoDao.class).clone();
        fatherUserInfoDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        fatherUserInfoDao = new FatherUserInfoDao(fatherUserInfoDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(FatherUserInfo.class, fatherUserInfoDao);
    }
    
    public void clear() {
        userInfoDaoConfig.getIdentityScope().clear();
        fatherUserInfoDaoConfig.getIdentityScope().clear();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public FatherUserInfoDao getFatherUserInfoDao() {
        return fatherUserInfoDao;
    }

}
