package com.koffuxu.myapplication.daogen;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FATHER_USER_INFO".
 */
public class FatherUserInfo {

    private String name;
    private Long id;

    public FatherUserInfo() {
    }

    public FatherUserInfo(Long id) {
        this.id = id;
    }

    public FatherUserInfo(String name, Long id) {
        this.name = name;
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
